### ISSUE TITLE
Kodi repository update.

### ISSUE THREAD

**Issue by Lunatixz** [marcelveldt/script.module.simplecache#6]
Hello, It looks like you already fixed the unreferenced "results" variable when memory is disabled :)
https://github.com/marcelveldt/script.module.simplecache/blob/master/lib/simplecache.py#L58

Any chance you can share your current updates with the Kodis repository? Thanks

**Comment by marcelveldt** [comment]
Sorry, yes. I need to update several of my addons on the repo. Have been really busy with personal life and work lately... Will do so within a few weeks, I promise.

If you'e in a hurry, I don't mind giving you write access to contribute

**Comment by Lunatixz** [comment]
No problem, it's up to you... far as write access. If you won't be able to create a PR; I can handle it =) Just let me know which masters are suitable for Kodis repository. THX

**Comment by marcelveldt** [comment]
Thanks for helping out!
As far as I'm aware most of my addons haven't been updated to the Kodi repo for a long time, while the functionality has actually been improved.

For example:

- script.skin.helper.service
- script.module.simplecache
- script.tv.show.next.aired
- script.skin.helper.backgrounds
- script.module.cherrypy (not sure if that is even on the repo yet)

I'm looking for time to take the challenge to submit it all to the kodi devs but my previous attempts were very time consuming, while my own repo has a simple button to just publish.

I you see some time do submit one or more addons to the repo, that would be great!
Feel free to append your name to the maintainers of the addons, I do not mind at all. In fact, I'm glas with every bit of help I can get as I have a lot of addons but only little time atm to maintain them all.

Shall I give you write access to some/all repos ?

**Comment by Lunatixz** [comment]
Write permission would be great. I'll bring Kodi's repo up to date. Thanks
